/**
 * This is auto-generated by code generator tools, DO NOT MODIFY MANUALLY!!!
 */
package com.allintechinc.taihang.workflow.service;

import com.allintechinc.taihang.form.SearchForm;
import com.allintechinc.taihang.workflow.dto.ApplyUserDto;
import com.allintechinc.taihang.workflow.dto.ProcessTaskDto;
import com.allintechinc.taihang.workflow.dto.ProcessTaskHistoryDto;
import com.allintechinc.taihang.workflow.form.ApplyUserForm;
import com.allintechinc.taihang.workflow.form.ProcessParamForm;
import com.allintechinc.taihang.workflow.form.ReviewForm;
import com.allintechinc.taihang.workflow.form.UserForm;
import org.springframework.data.domain.Page;

import java.util.List;

// Imports for Page
// Imports for SearchForm

/**
 * @author code generator tool
 */
public interface ProcessHandleRecordService {
    /**
     * 审批通过
     *
     * @param form
     * @return Void
     */
    public Void approved(ReviewForm form);

    /**
     * 驳回
     *
     * @param form
     * @return Void
     */
    public Void reject(ReviewForm form);

    /**
     * 查询流程处理记录列表
     *
     * @param searchForm
     * @return Page<ProcessHandlerRecordDto>
     */
    public Page<ProcessTaskHistoryDto> search(SearchForm searchForm);

    /**
     * 启动流程
     *
     * @param form
     * @return ProcessTaskDto
     */
    public ProcessTaskDto startProcessInstance(ProcessParamForm form);

    /**
     * 获取某个流程审批进度
     *
     * @param processId
     * @return List<ProcessHandlerRecordDto>
     */
    public List<ProcessTaskHistoryDto> detail(String processId);

    /**
     * 通过审批人信息和任务状态查询申请人列表
     *
     * @param form
     * @return List<ApplyUserDto>
     */
    public List<ApplyUserDto> getAllApplyUsers(ApplyUserForm form);

    /**
     * 根据任务编码获取任务审批信息
     *
     * @param taskId
     * @return ProcessHandlerRecordDto
     */
    public ProcessTaskHistoryDto findByTaskId(String taskId);

    /**
     * 我的申请流程列表
     *
     * @param searchForm
     * @return Page<ProcessHandlerRecordDto>
     */
    public Page<ProcessTaskHistoryDto> getOwnerApprove(SearchForm searchForm);


    /**
     * 获取流程基本信息
     *
     * @param processInstanceId
     * @return ProcessHandlerRecordDto
     */
    public ProcessTaskHistoryDto getProcess(String processInstanceId);

    /**
     * 查询流程定义、引擎中是否使用了该用户
     *
     * @param form
     * @return Boolean
     */
    public Boolean findUserFromWorkflow(UserForm form);
}