/**
 * This is auto-generated by code generator tools, DO NOT MODIFY MANUALLY!!!
 */
package com.allintechinc.taihang.workflow.service;


import com.allintechinc.taihang.form.SearchForm;
import com.allintechinc.taihang.workflow.dto.ProcessDefinitionDto;
import com.allintechinc.taihang.workflow.dto.ProcessTypeDto;
import com.allintechinc.taihang.workflow.form.ProcessDefinitionForm;
import org.springframework.data.domain.Page;

/**
 * @author code generator tool
 */
public interface ProcessRecordService {
    /**
     * 新建流程记录
     *
     * @param form
     * @return Long
     */
    public Long create(ProcessDefinitionForm form);


    /**
     * 获取某个流程记录
     *
     * @param id
     * @return ProcessRecordDto
     */
    public ProcessDefinitionDto detail(Long id);

    /**
     * 查询流程定义列表
     *
     * @param searchForm
     * @return Page<ProcessDefinitionDto>
     */
    public Page<ProcessDefinitionDto> search(SearchForm searchForm);

    /**
     * 获取流程类型列表
     *
     * @param
     * @return ProcessTypeDto
     */
    public ProcessTypeDto processTypeList();

    /**
     * 通过流程类型判断流程定义是否存在
     *
     * @param processType
     * @return Boolean
     */
    public Boolean exist(String processType);

}