/**
 * This is auto-generated by code generator tools, YOU *MUST* Implement all the methods!!!
 */
package com.allintechinc.taihang.workflow.exception;

import com.allintechinc.taihang.exception.BusinessException;

/**
 * @author sundp
 */
public class ProcessHandleRecordException extends BusinessException {
    private static final long serialVersionUID = -7719330114856947394L;

    public static final ProcessHandleRecordException PROCESS_INSTANCE_START_ERROR = new ProcessHandleRecordException("process.instance.start.error", "流程启动失败!");
    public static final ProcessHandleRecordException PROCESS_TASK_NOT_EXISTS = new ProcessHandleRecordException("process.task.not.exists", "需要审批的任务不存在!");
    public static final ProcessHandleRecordException PROCESS_BEAN_T_MAP_ERROR = new ProcessHandleRecordException("process.bean.to.map.error", "审批对象转换异常!");


    public ProcessHandleRecordException(String code, String message) {
        super(code, message);
    }

}
