server:
  port: 8081

## 数据源配置 (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:postgresql://db-test-01.allintechinc.com:5000/workflow
    username: taihang
    password: Allintihang20200609!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: update # DDL 级别(create, create-drop, validate, update)
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: true
    database-change-log-lock-table: flw_ev_databasechangeloglock
    database-change-log-table: flw_ev_databasechangelog
    url: jdbc:postgresql://db-dev-01.allintechinc.com:5000/workflow
    user: taihang
    password: taihuser@201911131203
    change-log: classpath:db/db_script_all.xml

  jackson:
    # 一定要注意这里是冒号,不是等号!!!
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

taihang:
  platform: taihang
  service-info:
    enable: true
  api-doc:
    enable: true
    api-version: 1.0
  json-log:
    enable: false

kafka:
  bootstrap-servers: 10.20.0.165:9092
  listener:
    missing-topics-fatal: false
  producer:
    retries: 3
    acks: all
    compression-type-config: gzip
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: allin-pubsub
    enable-auto-commit: false
    auto-commit-interval: 1000
    auto-offset-reset-config: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true