/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.allintechinc.taihang.workflow.api;

import com.allintechinc.taihang.form.SearchForm;
import com.allintechinc.taihang.workflow.dto.ProcessDefinitionDto;
import com.allintechinc.taihang.workflow.dto.ProcessTypeDto;
import com.allintechinc.taihang.workflow.form.ProcessDefinitionForm;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

// Imports for Page
// Imports for SearchForm
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringConfiguration", date = "2020-05-11T21:19:55.000+08:00")

/**
 * @author code generator tool
 */
public interface ProcessApi {
    /**
     * 新建流程定义
     *
     * @param form
     * @return Long
     */
    @RequestMapping(value = "/process/definition",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    Long create(@Valid @RequestBody ProcessDefinitionForm form);

    /**
     * 获取某个流程定义
     *
     * @param id
     * @return ProcessDefinitionDto
     */
    @RequestMapping(value = "/process/definition/{id}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ProcessDefinitionDto detail(@PathVariable("id") Long id);

    /**
     * 查询流程定义列表
     *
     * @param searchForm
     * @return Page<ProcessDefinitionDto>
     */
    @RequestMapping(value = "/process/definition/search",
            method = RequestMethod.POST)
    Page<ProcessDefinitionDto> search(@Valid @RequestBody SearchForm searchForm);

    /**
     * 获取流程类型列表
     *
     * @param
     * @return ProcessTypeDto
     */
    @RequestMapping(value = "/process/definition/process_type", method = RequestMethod.GET)
    ProcessTypeDto processTypeList();

    /**
     * 通过流程类型判断流程定义是否存在
     *
     * @param processType
     * @return Boolean
     */
    @RequestMapping(value = "/process/definition/exists/{process_type}", method = RequestMethod.GET)
    Boolean exist(@PathVariable("process_type") String processType);

}