/**
 * This is auto-generated by code generator tools, DO NOT MODIFY MANUALLY!!!
 */
package com.allintechinc.taihang.workflow.controller;

import com.allintechinc.taihang.annotaions.ResponseDecorated;
import com.allintechinc.taihang.form.SearchForm;
import com.allintechinc.taihang.workflow.api.ProcessApi;
import com.allintechinc.taihang.workflow.dto.ProcessDefinitionDto;
import com.allintechinc.taihang.workflow.dto.ProcessTypeDto;
import com.allintechinc.taihang.workflow.form.ProcessDefinitionForm;
import com.allintechinc.taihang.workflow.service.ProcessRecordService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringConfiguration", date = "2020-05-11T21:19:55.000+08:00")

/**
 * @author code generator tool
 */
@Slf4j
@RestController
@ResponseDecorated
@RequestMapping("/api/v1")
public class ProcessApiController implements ProcessApi {

    @Autowired
    ProcessRecordService service;

    @Override
    public Long create(ProcessDefinitionForm form) {

        return service.create(form);
    }

    @Override
    public ProcessDefinitionDto detail(Long id) {

        return service.detail(id);
    }

    @Override
    public Page<ProcessDefinitionDto> search(SearchForm searchForm) {

        return service.search(searchForm);
    }

    @Override
    public ProcessTypeDto processTypeList() {
        return service.processTypeList();
    }

    @Override
    public Boolean exist(String processType) {
        return service.exist(processType);
    }

}
